import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen`}>
        <Header />
        {children}
      </body>
    </html>
  );
}

function Header() {
  return (
    <header className="border-b">
      <nav className="flex justify-start p-4 space-x-4">
        <a href="/" className="text-2xl font-bold">
          Home
        </a>
        <a href="/about" className="text-2xl font-bold">
          About
        </a>
      </nav>
    </header>
  );
}
